### ISSUE TITLE
Filtering error (false positive)

### ISSUE THREAD

**Issue by vtvz** [finnbear/rustrict#12]
Hello there. It's me again with my profanity detector for Spotify songs. After [upgrade](https://github.com/vtvz/rustify/commit/e2ed1c8f07a54c69df79c31730afc59ea3ce79b0#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R26) I've got some interesting cases:

Detected parts framed with brackets

### False Positives
```
P(re-C)hours (lots of them, I don't even know which wort is it)
(Nig)thmares (there's a typo in word but still funny case)
Quo (fug)iam ab eorum spiritibus (I guess it's Latin language. I feel, You can ignore this edge case)
```

### Context

I am using `rustrict` version `rustrict = { version = "0.7.6", features = ["customize"] }` 

Question aside this issue: can I somehow get list of all detected words with its plain form? For example, rustrict redacted `s-h-i-t` and I get vector with one word `vec!["shit"]` back

PS: Thanks for the wonderful library. Good part of my project based on it :heart:

**Comment by finnbear** [comment]
FYI, I couldn't reproduce a detection with `Pre-Chours`. Feel free to comment or open a new issue with a reproducible case.

>  can I somehow get list of all detected words with its plain form? For example, rustrict redacted s-h-i-t and I get vector with one word vec!["shit"] back

This is possible to implement as a feature flag in the future. It will have significant memory overhead and some CPU overhead.

> PS: Thanks for the wonderful library. Good part of my project based on it :heart:

np :heart:

**Comment by vtvz** [comment]
Interesting. Need more investigation

![screenshot](https://github.com/finnbear/rustrict/assets/11929252/d0fe9c1f-f19e-4883-ace5-50d66a221550)

**Comment by finnbear** [comment]
> Interesting. Need more investigation

I get the sense that the filter thinks it's looking at "reich" (which is "mildly offensive") but I still don't quite see how it interpreted a '-' (or '-' lookalike) as 'i'.

**Comment by vtvz** [comment]
Caught it

```
pub fn check_cases() {
    let cases = ["\\[Pre\\-Chorus\\]"];

    cases.map(|case| {
        let (censored, typ) = rustrict::Censor::from_str(case)
            .with_censor_first_character_threshold(Type::ANY)
            .with_censor_threshold(Type::ANY)
            .censor_and_analyze();

        println!("{:?} {:?} {:?}", case, censored, typ);
    });
}
```
Output

```
"\\[Pre\\-Chorus\\]" "\\[P******orus\\]" mildly offensive
```

I guess it treats `\` as `I`?

**Comment by finnbear** [comment]
> I guess it treats `\` as `I`?

Yeah, P**re\\-Ch**orus -> P**re\\ch**Crus -> **reich**.

Fixing this would involve any of:
- You finding some way to avoid passing all of the \'s to rustrict i.e. don't pass things the user wont actually see in the end
- Me removing reich from the word list, keeping things like 'third reich'
- Me changing certain thresholds until replacing \ -> i makes this particular detection go away (hard)

**Comment by vtvz** [comment]
Unfortunately, I need to "pre-escape" all those characters to pass them to the telegram API. But I found the solution: add this particular case to safe type)

**Comment by finnbear** [comment]
> Unfortunately, I need to "pre-escape" all those characters to pass them to the telegram API. But I found the solution: add this particular case to safe type)

Sure! Another, more general, idea is to remove most replacement characters:

```
let r = Replacements::new();
for c in 'A'..='Z' {
    r.insert(c, c.to_ascii_lowercase());
}
*Replacements::customize_default() = r;
```
(I didn't actually try to compile this but the general idea is that Spotify Music probably doesn't have evasive replacements like / instead of I).

**Comment by vtvz** [comment]
BTW this works:
```rust
{
    let mut r = Replacements::new();
    for b in b'a'..=b'z' {
        let c = b as char;
        r.insert(c, c); // still detect lowercased profanity.
        r.insert(c.to_ascii_uppercase(), c); // still detect capitalized profanity.
    }

    unsafe {
        *Replacements::customize_default() = r;
    }
}
```
tnx)
