### ISSUE TITLE
Add tags to every published version

### ISSUE THREAD

**Issue by vtvz** [finnbear/rustrict#17]
I love exploring source code of my favourite libs. In this case, I especially need it to compare changes in dictionaries. It's not very convenient to search commit history

**Comment by finnbear** [comment]
I'll try to remember to do this going forward. Seems time consuming to do retroactively.

**Comment by vtvz** [comment]
Love your work. It's the heart of my project. Don't want it to be abandoned :heart:

**Comment by finnbear** [comment]
Thanks for the comment and sponsorship! At the moment, I have a vested interest in maintaining `rustrict` to protect the chats of the games I work on. That won't change in the foreseeable future :)

Closing as plan has been formed: https://github.com/finnbear/rustrict/issues/17#issuecomment-1781583601
