### ISSUE TITLE
CGO Wrapper

### ISSUE THREAD

**Issue by mprimeaux** [finnbear/rustrict#22]
### Motivation

Given the Go-based version, []() is not longer actively maintained, it would be nice to still be able to call this from Go. The request is for the creation of a CGO wrapper maintained in this repository to ensure API changes are part of the branching strategy of this repository. 

### Alternatives

I'd prefer not to fork `moderation` and maintain it or find an Go-based alternative.

### Context

I am not using rustrict but am using [moderation](https://github.com/mprimeaux/moderation).

**Comment by finnbear** [comment]
Thanks for the issue. At the moment, a Go version is not useful to me personally, would require research for me to implement, and is out of scope of this repository. There is precedent for creating bindings in a 3rd party location: https://github.com/nooptoday/profanity-filter / https://www.npmjs.com/package/@nooptoday/profanity-filter. If you created a Go wrapper, I'd be happy to link to it and the JS wrapper in a new part of my README.

Note: I'm curious if Go users would have to have a Rust compiler, as implied by https://github.com/arjanvaneersel/go-rust/blob/b3e53450e892504ec52eb1bac8a80fb03fa742cb/lib/hello/Makefile#L2 or if it would be pre-compiled.
