### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by callmeclover** [finnbear/rustrict#23]
people in my chat app have been using the character '∁' to get around this beautiful filter
I will also be submitting issues or PRs for anything that evades your filter.
In rustrict we trust.

(the version I'm using is whatever one was in the bindings I made for Elixir, called [Bartender.](https://github.com/stalepretzels/bartender)

**Comment by finnbear** [comment]
Thanks for opening this. I've fixed the issue you brought up in `0.7.23`, along with all other characters its Unicode block and the following Unicode block.
