### ISSUE TITLE
Typing in Context?

### ISSUE THREAD

**Issue by callmeclover** [finnbear/rustrict#25]
Hi, I was reading over the docs, and I couldn't find a way to censor `Type::SEVERE | Type::OFFENSIVE` only. Is there a way to do this already? If not, could this be implemented? Thanks!

EDIT: Forgot to mention this is to do with the `context` feature 😅

**Comment by finnbear** [comment]
The API for censoring a specific `rustrict::Type` works like this:
```rust
let censored = rustrict::Censor::from_str("some input")
    .with_censor_threshold(typ)
    .with_censor_first_character_threshold(typ)
    .censor();
```

As for the value of `typ`, consider the following options:
- `rustrict::Type::SEVERE | rustrict::Type::OFFENSIVE` includes
  - mildly offensive
  - moderately offensive
  - severely offensive
  - severely profane
  - severely sexual
  - severely mean
  - severely evasive
  - severely spammy
  - severely [any future category]
- `rustrict::Type::SEVERE & rustrict::Type::OFFENSIVE` includes
  - severely offensive

If you want something other than those two options, please describe it!

**Comment by callmeclover** [comment]
Does this still work with `Context`? Would it just be
```rust
...process()
    .with_censor_threshold(typ)
    .with_censor_first_character_threshold(typ)
```
or is there some other way to implement this?

**Comment by finnbear** [comment]
Ah, I see. That's not currently possible. `Context` selects a `Type` at runtime, depending on message history.

While the following advice isn't documented anywhere, I recommend using `Context` as a model of how to use `rustrict`, that you can copy and adapt. It only makes sense to `use rustrict::Context` in your application if you have very similar needs as me. I've received some good advice that it should be removed from the library, possibly leaving it in `examples`.

**Comment by callmeclover** [comment]
Alright then, I mean, the features wouldn't really be hard to implement myself, so I suppose I'll just swap out with a basic `Censor`.
