### ISSUE TITLE
Filtering error (false positive)

### ISSUE THREAD

**Issue by vtvz** [finnbear/rustrict#4]
### False Positives
The following shouldn't have been detected, but was:
```
ain't it
really didn't (It turns out)
honkey-tonk // I suppose honkey-tonk is not a bad word, but I don't really know
I get lost
```

### Context

I am using `rustrict` version `0.3.14`

Code sample:
```rust
    let cases = [
        "ain't it",
        "really didn't (It turns out)",
        "honkey-tonk",
        "I get lost",
    ];

    cases.map(|case| {
        let (censored, typ) = rustrict::Censor::from_str(case)
            .with_censor_first_character_threshold(Type::ANY)
            .with_censor_threshold(Type::ANY)
            .censor_and_analyze();

        println!(
            "{:?} {:?} {:#b} ({})",
            case,
            censored,
            typ,
            TypeWrapper(typ)
        );
    });
```
Outputs
```rust
"ain't it" "ain'****" 0b10000000 (moderate sexual 🟠)
"really didn't (It turns out)" "really didn'***** turns out)" 0b10000000 (moderate sexual 🟠)
"honkey-tonk" "******-tonk" 0b10000 (moderate offensive 🟠)
"I get lost" "I ********" 0b10000000000 (moderate mean 🟠)
```

**Comment by finnbear** [comment]
Hi there,

Thanks for the comprehensive report! I have fixed all these cases and more for version `0.4.0`.

The reason for a version bump from `0.3.x` to `0.4.x` is I noticed that you are writing manual code (or copying code from this repository) to debug `Type` as a string like `moderate sexual`. I wanted to make it easier, so I made `Type` into a new-type that encapsulates the `bitflags` type. That allowed me to `impl Debug for Type`, so now you can `println!("{:?}", type)`. Please let me know if there is any notable incompatibility between the new `Type` and the old `Type`.

**Comment by vtvz** [comment]
It's not only for debugging. It's also for reporting. Message from bot looks mostly like this:
![image](https://user-images.githubusercontent.com/11929252/153874167-e7f21b52-0562-44b4-a25e-cf28cded4ee6.png)

But having the out-of-the-box way to represent types as strings would be super nice. It will create such reports even more obvious and representative for the main contributors.  

P.S. With Rust I don't afraid of breaking changes)

**Comment by finnbear** [comment]
Closing as resolved by `0.4.0` :tada:

**Comment by vtvz** [comment]
@finnbear One thing that broke is `println!("{:#b}", typ);`. It's not critical for me at all, I just used it to send you bitmask for debugging. But it's worth mentioning, I think
```
error[E0277]: the trait bound `rustrict::Type: std::fmt::Binary` is not satisfied
   --> src/profanity.rs:187:53
    |
187 |         println!("{:?} {:?} {:#b}", case, censored, typ);
    |                                                     ^^^ the trait `std::fmt::Binary` is not implemented for `rustrict::Type`
    |
note: required by a bound in `ArgumentV1::<'a>::new_binary`
   --> /home/vtvz/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/fmt/mod.rs:344:5
    |
344 |     arg_new!(new_binary, Binary);
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `ArgumentV1::<'a>::new_binary`
    = note: this error originates in the macro `$crate::format_args_nl` (in Nightly builds, run with -Z macro-backtrace for more info)

```

**Comment by vtvz** [comment]
But this debug thingy works wonderfully :blush: 
![image](https://user-images.githubusercontent.com/11929252/154453231-e3422bd9-2cc6-44ad-9697-5b998fcbed72.png)
